In [1]:
import numpy as np
import math as m

def BOPM(n,t,S,v):
    dt = t/n                #n = no. of time steps
    u = m.exp(v*m.sqrt(dt)) #up 
    d = 1/u                 #down
    Pm = np.zeros((n+1, n+1))
    for j in range(n+1):
        for i in range(j+1):
            Pm[i,j] = S*m.pow(d,i) * m.pow(u,j-i)
    return Pm

In [2]:
n = 5
t = 200/365
S = 100
v = .3
x = BOPM(n,t,S,v)
n = 17
z = BOPM(n,t,S,v)

print('Pricing Tree for n = 5:\n',np.matrix(x.astype(int)))
print('Pricing Tree for n = 17:\n',np.matrix(z.astype(int)))

Pricing Tree for n = 5:
 [[100 110 121 134 148 164]
 [  0  90 100 110 121 134]
 [  0   0  81  90 100 110]
 [  0   0   0  74  81  90]
 [  0   0   0   0  67  74]
 [  0   0   0   0   0  60]]
Pricing Tree for n = 17:
 [[100 105 111 117 124 130 138 145 153 162 171 180 190 201 212 224 236 249]
 [  0  94 100 105 111 117 124 130 138 145 153 162 171 180 190 201 212 224]
 [  0   0  89  94 100 105 111 117 124 130 138 145 153 162 171 180 190 201]
 [  0   0   0  85  89  94  99 105 111 117 124 130 138 145 153 162 171 180]
 [  0   0   0   0  80  85  89  94 100 105 111 117 124 130 138 145 153 162]
 [  0   0   0   0   0  76  80  85  89  94 100 105 111 117 124 130 138 145]
 [  0   0   0   0   0   0  72  76  80  85  89  94  99 105 111 117 124 130]
 [  0   0   0   0   0   0   0  68  72  76  80  85  89  94  99 105 111 117]
 [  0   0   0   0   0   0   0   0  64  68  72  76  80  85  89  94 100 105]
 [  0   0   0   0   0   0   0   0   0  61  64  68  72  76  80  85  89  94]
 [  0   0   0   0   0   0   0   0   

In [3]:
def OptionsVal(n, S, K, r, v, T, PC):
    dt = T/n                #n = no. of time steps
    u = m.exp(v*m.sqrt(dt)) #up 
    d = 1/u                 #down
    p = (m.exp(r*dt)-d)/(u-d)
    Pm = np.zeros((n+1, n+1))
    Cm = np.zeros((n+1, n+1))
    for j in range(n+1):
        for i in range(j+1):
            Pm[i,j] = S*m.pow(d,i) * m.pow(u,j-i)
    for j in range(n+1, 0, -1):
        for i in range(j):
            if (PC == 1):                               
                if(j == n+1):
                    Cm[i,j-1] = max(K-Pm[i,j-1], 0)     
                else:
                    Cm[i,j-1] = m.exp(-.05*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j]) 
            if (PC == 0):                               
                if (j == n + 1):
                    Cm[i,j-1] = max(Pm[i,j-1]-K, 0)     
                else:
                    Cm[i,j-1] = m.exp(-.05*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j])  
    return [Pm,Cm] 

In [6]:
S = 100
k = 100
r = .05
v = .3
T = 20/36
n = 17
PC = 0      # 0 for Call and 1 for Put
Pm,CmC = OptionsVal(n,S,k,r,v,T,PC)
PC = 1
_,CmP= OptionsVal(n, S, k, r, v, T, PC)
print('Pricing Tree:\n',np.matrix(Pm.astype(int)))
print('Call Option Tree:\n',np.matrix(CmC.astype(int)))
print('Put Option Tree:\n',np.matrix(CmP.astype(int)))

Pricing Tree:
 [[100 105 111 117 124 131 138 146 154 162 172 181 191 202 213 225 238 251]
 [  0  94 100 105 111 117 124 131 138 146 154 162 172 181 191 202 213 225]
 [  0   0  89  94 100 105 111 117 124 131 138 146 154 162 172 181 191 202]
 [  0   0   0  84  89  94 100 105 111 117 124 131 138 146 154 162 172 181]
 [  0   0   0   0  80  84  89  94 100 105 111 117 124 131 138 146 154 162]
 [  0   0   0   0   0  76  80  84  89  94 100 105 111 117 124 131 138 146]
 [  0   0   0   0   0   0  72  76  80  84  89  94 100 105 111 117 124 131]
 [  0   0   0   0   0   0   0  68  72  76  80  84  89  94 100 105 111 117]
 [  0   0   0   0   0   0   0   0  64  68  72  76  80  84  89  94 100 105]
 [  0   0   0   0   0   0   0   0   0  61  64  68  72  76  80  84  89  94]
 [  0   0   0   0   0   0   0   0   0   0  58  61  64  68  72  76  80  84]
 [  0   0   0   0   0   0   0   0   0   0   0  55  58  61  64  68  72  76]
 [  0   0   0   0   0   0   0   0   0   0   0   0  52  55  58  61  64  68]
 [  0   0 